---

default_language_version:
    python: python3.11
minimum_pre_commit_version: 3.6.0

repos:

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except==0.2.1
          - flake8-bugbear==23.1.20
          - flake8-builtins==2.1.0
          - flake8-comprehensions==3.10.1
          - flake8-debugger==4.1.2
          - flake8-executable==2.1.3
          - flake8-logging-format==0.9.0
          - flake8-mutable==1.2.0
          - flake8-pie==0.16.0
          - flake8-print==5.0.0
          - flake8-pytest==1.4
          - flake8-string-format==0.3.0
          - pep8-naming==0.13.3
        types: [file, python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: debug-statements
        types: [file, python]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: fix-byte-order-marker
        exclude: (.*\.csv$)|(^.bumpversion.cfg$)|(^\.idea/.*$)
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: (.*\.csv$)|(^.bumpversion.cfg$)|(^\.idea/.*$)

  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        types: [file, python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
          - 'types-requests'
          - 'types-setuptools'

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "venv/bin/python -m pytest -x --no-cov -q > /dev/null"
        pass_filenames: false
        language: system
        types: [python]
